language: objective-c
osx_image: xcode12.5
script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace DemoProject.xcworkspace -scheme DemoProject-Dev -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO build | xcpretty
before_install:
  - bundle install
  - bundle exec pod install --repo-update



