language: objective-c
osx_image: xcode12.5
#xcode_project: DemoProject.xcodeproj
xcode_workspace: DemoProject.xcworkspace
xcode_scheme: DemoProject-Dev
xcode_destination: platform:iOS Simulator, id:88B3BB38-4B0D-4C69-8C10-3D19F1D9D785, OS:14.5, name:iPhone 12 Pro
before_install:
  - bundle install
  - bundle exec pod install --repo-update

