language: objective-c
#osx_image: xcode12.5
#script:
#  - set -o pipefail
#  - xcodebuild -workspace DemoProject.xcworkspace -scheme DemoProject-Dev -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO build | xcpretty
#before_install:
#  - bundle install
#  - bundle exec pod install --repo-update



#language: objective-c
#osx_image: xcode12.5
##xcode_project: DemoProject.xcodeproj
#xcode_workspace: DemoProject.xcworkspace
#xcode_scheme: DemoProject-Dev
#xcode_destination: platform:iOS Simulator, OS:14.5, name:iPhone 12 Pro
#before_install:
#  - bundle install
#  - bundle exec pod install --repo-update

language: objective-c
xcode_workspace: DemoProject.xcworkspace
xcode_scheme: DemoProject-Dev
xcode_destination: platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro
before_install:
  - bundle install
  - bundle exec pod install --repo-update
