language: objective-c
osx_image: xcode12.5
#xcode_project: DemoProject.xcodeproj
xcode_workspace: DemoProject.xcworkspace
xcode_scheme: DemoProject-Dev
xcode_destination: platform=iOS Simulator, OS:14.5, name:iPhone 12 Pro
before_install:
  - bundle install
  - bundle exec pod install --repo-update

