language: objective-c
osx_image: xcode12.5
script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace DemoProject.xcworkspace -scheme DemoProject-Dev -destination "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO build | xcpretty
before_install:
  - bundle install
  - bundle exec pod install --repo-update
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 12 Pro (14.5)" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a simulator --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID



