language: objective-c
osx_image: xcode12.5
script:
  - set -o pipefail
  - xcodebuild -workspace DemoProject.xcworkspace -scheme DemoProject-Dev -destination "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO build | xcpretty
before_install:
  - bundle install
  - bundle exec pod install --repo-update



